In [1]:
import numpy as np

In [2]:
np.random.default_rng(1)
np.random.seed(1)

In [3]:
A = np.round((np.random.rand(5, 5) * 10) - 5 + 20* np.eye(5,5), 3)
f = np.round((np.random.rand(5) * 10 - 5), 3)

In [4]:
A

array([[19.17 ,  2.203, -4.999, -1.977, -3.532],
       [-4.077, 16.863, -1.544, -1.032,  0.388],
       [-0.808,  1.852, 17.045,  3.781, -4.726],
       [ 1.705, -0.827,  0.587, 16.404, -3.019],
       [ 3.007,  4.683, -1.866,  1.923, 23.764]])

In [5]:
f

array([ 3.946, -4.15 , -4.609, -3.302,  3.781])

In [6]:
def checkConvergence(A):
    n = A.shape[0]

    for i in range(n):
        sum = 0
        for a in np.abs(A[i, :]):
            sum += a

        sum -= np.abs(A[i, i])

        if A[i,i] <= sum:
            return False
            
    return True

In [8]:
checkConvergence(A)

True

In [7]:
def jacobiSolver(A, f, eps=1e-12, maxIters=1000):
    n = A.shape[0]

    x = np.zeros(n)

    for k in range(maxIters):
        x_new = np.zeros(n)

        for i in range(n):
            sum = 0

            for j in range(n):
                if j!=i:
                    sum+=A[i, j]*x[j]

            x_new[i] = (f[i] - sum) / A[i, i]

        if np.max(np.abs(x_new - x)) < eps:
            return x_new, k+1

        x = x_new

    return x, k+1

In [9]:
jacobiSolver(A, f)

(array([ 0.20791404, -0.22501991, -0.14227827, -0.19569615,  0.18180454]), 25)

In [10]:
A = np.round((np.random.rand(5, 5) * 10) - 5 + 0* np.eye(5,5), 3)
f = np.round((np.random.rand(5) * 10 - 5), 3)

In [11]:
A

array([[-4.017, -0.789,  4.579,  0.332,  1.919],
       [-1.845,  1.865,  3.346, -4.817,  2.501],
       [ 4.889,  2.482, -2.196,  2.893, -3.968],
       [-0.521,  4.086, -2.064, -2.122, -3.7  ],
       [-4.806,  1.788, -2.884, -2.345, -0.084]])

In [12]:
f

array([-4.466,  0.741, -3.533,  0.893,  1.998])

In [13]:
checkConvergence(A)

False

In [14]:
jacobiSolver(A, f)

/tmp/ipykernel_319592/1548592516.py:14: RuntimeWarning: overflow encountered in scalar multiply
  sum+=A[i, j]*x[j]
/tmp/ipykernel_319592/1548592516.py:14: RuntimeWarning: overflow encountered in scalar add
  sum+=A[i, j]*x[j]
/tmp/ipykernel_319592/1548592516.py:16: RuntimeWarning: overflow encountered in scalar divide
  x_new[i] = (f[i] - sum) / A[i, i]
/tmp/ipykernel_319592/1548592516.py:14: RuntimeWarning: invalid value encountered in scalar add
  sum+=A[i, j]*x[j]
/tmp/ipykernel_319592/1548592516.py:18: RuntimeWarning: invalid value encountered in subtract
  if np.max(np.abs(x_new - x)) < eps:


(array([nan, nan, nan, nan, nan]), 1000)